### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by arimorty** [xioxin/dynamic_widget_builder#1]
This is great work and is useful to me, but I can't use it until there is a license.

**Comment by xioxin** [comment]
MIT License

I'm trying other dynamic solutions, and this project may no longer be maintained.

**Comment by arimorty** [comment]
Okay, thanks. 

But hey, this can be really useful, see below:

**this is why the library was useful to me:**
it enables to write Flutter code in any file and then convert it to .ts easily and then finally to .json

I created a script that successfully does this:
- read real Flutter widget code from .dart file
- add "{" and "}" where it's needed and write it to a .ts file
- compile the .ts file 
- reference the .ts variable containing the widget code and convert it to json
